### ISSUE TITLE
Initial Tasks

### ISSUE THREAD

**Issue by venilnoronha** [spring-cloud-incubator/spring-cloud-config-server-mongodb#1]
@spencergibb could you please help me with the following?
- [X] Travis setup 
- [x] Maven deployment configuration
- [X] Gitter setup

**Comment by spencergibb** [comment]
I'd look at https://github.com/opendiscovery/opendiscovery-java/.travis.yml for tips on travis and https://artifactory.jfrog.org/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org for deploying snapshots to oss.jfrog.org.

**Comment by venilnoronha** [comment]
I'm unable to set up travis due to some permissions error.

![travis-ci](https://cloud.githubusercontent.com/assets/1722758/15983182/c2320b18-2fbc-11e6-8c37-189caedbd919.png)

**Comment by spencergibb** [comment]
Right, I'll set that up

**Comment by venilnoronha** [comment]
Cool, thanks!

**Comment by venilnoronha** [comment]
It'd be great if you could also enable [gitter](https://gitter.im/spring-cloud-incubator/spring-cloud-config-server-mongodb) for this repo.

**Comment by spencergibb** [comment]
Travis is enabled.

**Comment by venilnoronha** [comment]
Great!

**Comment by spencergibb** [comment]
gitter is done too.

**Comment by venilnoronha** [comment]
Awesome! Thanks a lot :)

**Comment by venilnoronha** [comment]
Maven snapshot deployment is configured.

```
<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-config-server-mongodb</artifactId>
        <version>0.0.1.BUILD-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>ojo-snapshots</id>
        <name>OJO Snapshots</name>
        <url>https://oss.jfrog.org/artifactory/libs-snapshot</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by Fogetti** [comment]
Hi guys, thanks for the efforts!

Just wanted to note that the dependency resolution fails in Gradle since the transitive dependency `spring-cloud-build:1.0.0.BUILD-SNAPSHOT` is not contained in the `OJO Snapshots` repository.

Maybe the same thing happens in Maven also. I don't know, I haven't tried.

I solved it by adding the `https://repo.spring.io/libs-snapshot-local` also to the repository list. Maybe it's worth mentioning in the documentation.

**Comment by venilnoronha** [comment]
Thanks for notifying! I'll add it to the document.
